### ISSUE TITLE
Preset recall fails for preset numbers >127

### ISSUE THREAD

**Issue by gbaseman** [vwout/obs-visca-control#14]
For cameras supporting greater than 128 presets (such as PTZOptics 30x zoom models), attempting to recall preset numbers greater than 127 result in the wrong preset number being recalled.

**Comment by vwout** [comment]
Thanks for reporting this. The 'official' Sony specification states the maximum preset number is 63. Other manufacturers specify larger maximum preset values. 
The plugin indeed limits the maximum preset number to 127, but does not warn in case a higher number is configured. I will change the behavior to support 254 as maximum preset number and to provide feedback in the OBS interface instead of silently recalling preset 127 for any higher value.

**Comment by vwout** [comment]
Issue is resolved in release 2.4.
