### ISSUE TITLE
Modify camera moving speed

### ISSUE THREAD

**Issue by PoWeR-Ding** [vwout/obs-visca-control#6]
@vwout How have you been?

I hope to have two shortcut keys to increase and decrease the camera's moving speed.

**Comment by vwout** [comment]
Hi @PoWeR-Ding,

Which moving speed are you referring to? The speed of moves triggered by another shortcut key? And in that case, do you want to dynamically change the moving speed, or change the default (hard coded) moving speed for short-cut operations?

**Comment by PoWeR-Ding** [comment]
@vwout 
change the default (hard coded) moving speed for short-cut operations~

**Comment by PoWeR-Ding** [comment]
@vwout Incremental type，each press will carry out a value of +1 or - 1.

**Comment by PoWeR-Ding** [comment]
@vwout
I mainly mean "actions.PanTilt" speed  ！！ 
![微信截图_20221022115959](https://user-images.githubusercontent.com/112599924/197318155-47a64de8-8705-42bc-887b-f0ad957873b1.png)

**Comment by vwout** [comment]
Could you please test HEAD? I added pan/tilt and zoom/focus speeds to the camera settings in the script settings, so the values are no longer hard-coded. These values can be modified by shortcuts than can be configured in OBS settings.

**Comment by PoWeR-Ding** [comment]
👍I can cooperate in the test. But I don't know what HEAD is.


😆I added functions by studying your code
And the test has taken effect..


![微信截图_20221024085559](https://user-images.githubusercontent.com/112599924/197429529-737cfebf-5017-49d2-b903-b65c82bc30de.png)

**Comment by PoWeR-Ding** [comment]
Test VISCA message?


![微信截图_20221024100421](https://user-images.githubusercontent.com/112599924/197433981-0b1fd165-a8bf-48c4-bf6f-6743f250e892.png)

**Comment by vwout** [comment]
Hi @PoWeR-Ding, HEAD is the latest revision of a git repo, since you build OBS yourself, I guessed you were familiar with the term.

To test the changes I applied, download the sources (https://github.com/vwout/obs-visca-control/archive/refs/heads/main.zip) and copy [libvisca.lua](https://github.com/vwout/obs-visca-control/blob/main/libvisca.lua), [ljsocket.lua](https://github.com/vwout/obs-visca-control/blob/main/ljsocket.lua) and [obs-visca-control.lua](https://github.com/vwout/obs-visca-control/blob/main/obs-visca-control.lua) to the location where you installed this script plugin for OBS.

When you start OBS (or reload the script in OBS), you should see sliders with each camera in the script settings section and the ability to assign a hotkey in the OBS settings.

**Comment by PoWeR-Ding** [comment]
@vwout 

🙉 🙊You are really "awesome". Let me test it.👏 👏 

![微信图片_20221024142506](https://user-images.githubusercontent.com/112599924/197461074-a1733199-dfd7-46ce-83b1-40b0dd9bb9e2.jpg)

![微信图片_20221024142502](https://user-images.githubusercontent.com/112599924/197461098-7d31b351-b704-4223-8a63-049b63301e63.jpg)

**Comment by PoWeR-Ding** [comment]
@vwout 

Can Brightness and ColorSaturation also be added? please please😟😟

![微信截图_20221024144902](https://user-images.githubusercontent.com/112599924/197464449-75783421-d60f-482a-9969-bb5f1df6ceea.png)
